import 'package:pointycastle/pointycastle.dart';

/// A class to hold the keys generated by the EccManager.
///
/// Contains:
/// - ECPublicKey
/// - ECPrivateKey
/// - Base64 encoded public key
/// - Base64 encoded private key
class EccKeys {
  EccKeys({
    required this.publicKey,
    required this.privateKey,
    required this.publicKeyBase64,
    required this.privateKeyBase64,
  });

  final ECPublicKey publicKey; // The generated public key
  final ECPrivateKey privateKey; // The generated private key
  final String publicKeyBase64; // Base64 representation of the public key
  final String privateKeyBase64; // Base64 representation of the private key
}
